# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e20b8ca12e2e69a7b3c6944f2d03d5948f939f60b1860ca2b977f41ac899cd22992c6c5b9018ad353d33a35c9c93ae3106d260b6d9e0c4574085034b05b51699

test:
  secret_key_base: 8345d9cf3304a675e07f2ea2d83dd20ef9188cea9d80d8a465e2ea9b2fe423ac835f7d724a1a5a59544d6b8209cd0f87fe7d60e76bdb00cde988b8fd9811c4fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
